#!/usr/bin/env python3
"""Generate the Quantumult X reject filter from the Shadowrocket ad list."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Shadowrocket" / "rule" / "ad_black.list"
TARGET = ROOT / "QuantumultX" / "filter" / "ad_black.conf"

TYPE_MAP = {
    "DOMAIN-SUFFIX": "host-suffix",
    "DOMAIN": "host",
    "DOMAIN-WILDCARD": "host-wildcard",
    "DOMAIN-KEYWORD": "host-keyword",
    "IP-CIDR": "ip-cidr",
    "IP-CIDR6": "ip6-cidr",
    "IP-ASN": "ip-asn",
}

SKIPPED_TYPES = {"URL-REGEX"}


def build_filter() -> tuple[str, int, int]:
    output = [
        "# Generated by scripts/generate_quantumultx.py; do not edit manually.",
        "# Source: Shadowrocket/rule/ad_black.list",
        "# Skipped source type: URL-REGEX.",
        "",
    ]
    generated = 0
    skipped = 0

    for line_number, raw_line in enumerate(
        SOURCE.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith(("#", ";", "//")):
            continue

        parts = [part.strip() for part in line.split(",")]
        source_type = parts[0].upper()
        if source_type in SKIPPED_TYPES:
            skipped += 1
            continue
        if source_type not in TYPE_MAP:
            raise ValueError(
                f"{SOURCE.relative_to(ROOT)}:{line_number}: unsupported type "
                f"{source_type}"
            )
        if len(parts) not in (2, 3):
            raise ValueError(
                f"{SOURCE.relative_to(ROOT)}:{line_number}: expected 2 or 3 fields"
            )

        qx_rule = [TYPE_MAP[source_type], parts[1], "reject"]
        if len(parts) == 3:
            if source_type not in {"IP-CIDR", "IP-CIDR6"} or parts[2] != "no-resolve":
                raise ValueError(
                    f"{SOURCE.relative_to(ROOT)}:{line_number}: unsupported option "
                    f"{parts[2]}"
                )
            qx_rule.append("no-resolve")

        output.append(",".join(qx_rule))
        generated += 1

    return "\n".join(output) + "\n", generated, skipped


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the generated file differs from the committed file",
    )
    args = parser.parse_args()

    content, generated, skipped = build_filter()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            print(
                f"{TARGET.relative_to(ROOT)} is stale; run "
                "python3 scripts/generate_quantumultx.py",
                file=sys.stderr,
            )
            return 1
    else:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(content, encoding="utf-8")

    action = "validated" if args.check else "generated"
    print(f"{action} {generated} rules; skipped {skipped} unsupported rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
